#!/bin/zsh

##? tailf - `tail -f` with prefixed newlines instead of trailing
##?
##? usage: tailf <file>

# function tailf {
local nl
tail -f $2 | while read j; do
  print -n "$nl$j"
  nl="\n"
done
# }
